objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>RAJ</fullName>
                    <default>true</default>
                    <label>RAJ</label>
                </value>
                <value>
                    <fullName>CBSE</fullName>
                </value>
                <value>
                    <fullName>BIHAR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClassTeacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ClassTeacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ClassTeacher</relationshipLabel>
        <relationshipName>ClassTeacher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Status__c</fullName>
        <label>Custom Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>Reset</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ManageClassController.cls
public class ManageClassController {
    
    public string clsId{get; set;}
    public Class__c Cls{get; set;}
    public Map<ID,Class__C> mapOfCls{get;set;} 
    
    public ManageClassController(){
        clsId = '';
        mapOfCls = new Map<ID,Class__C>([Select class__c.name,Class__c.Board__c,Class__c.ClassTeacher__c,Class__c.Custom_Status__c from class__C]);
    }
    
    
    public void classDetail(){
        this.cls = mapOfCls.get(clsId);
    }
    
    
    public void classDelete(){
        this.cls = mapOfCls.get(clsId);
        delete cls;
        mapOfCls.remove(clsId);
            clsId = '';
    }
    
    public Void saveClass(){
        try{
            update Cls;
            clsId = '';
        }catch(Exception e){
        }
    }
    
}