objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Student</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PairClassStudent.cls
public class PairClassStudent {
    public static Map<String, List<Student__c>> getDataClassAndStudentID(){
      Map<String, List<Student__c>> m = new Map<String, List<Student__c>>();
        List<Class__c> c =  [select Name, ID from class__c];
          for(Integer i=0;i<c.size();i++){
              List<student__c> students=[SELECT ID from student__c];
              m.put(c[i].Name,students);
          }
        System.debug(m);
        return m;
    }
}